import type { Metadata } from "next";
import "./globals.css";
import { Pagefooter } from "./components/Pagefooter";
import { Pageheader } from "./components/Pageheader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Pageheader />
        {children}
        <Pagefooter />
      </body>
    </html>
  );
}
